version: '3'

services:
  adopt:
    container_name: 'adopt'
    build: ./adopt
    volumes:
      - ./src:/src
      - ./adopt:/out
  corretto:
    container_name: 'corretto'
    build: ./corretto
    volumes:
      - ./src:/src
      - ./corretto:/out
    depends_on:
      - adopt
  ibmsdk:
    container_name: 'ibmsdk'
    build: ./ibmsdk
    volumes:
      - ./src:/src
      - ./ibmsdk:/out
    depends_on:
      - corretto

